apiVersion: v1
kind: Service
metadata:
  name: kummo-flask-app-green
  labels:
    app: kummo-flask-app
spec:
  type: LoadBalancer
  selector:
    app: kummo-flask-app
    version: 2-0
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP