apiVersion: v1
kind: Service
metadata:
  name: kummo-flask-app
  labels:
    app: kummo-flask-app
spec:
  type: LoadBalancer
  selector:
    app: kummo-flask-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP